name: Build and deploy Jekyll site to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 setup
        uses: actions/checkout@v7

      - name: 💎 setup ruby
        uses: ruby/setup-ruby@v1.321.0
        with:
          ruby-version: 3.3

      - name: 🔨 install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2

      - name: 🚀 deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
